version: '3.0'
services:
  postgres:
      image: postgres
      container_name: postgres
      environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASS}
          - POSTGRES_DB=airflow

  airflow-newspipe:
    build: 
      context: airflow-newspipe-docker/
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
    container_name: airflow_newspipe
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/airflow/dags
      - ./output:/output
      - ./logs:/airflow/logs
    environment:
      - MONGO_ROOT_USER=${MONGO_ROOT_USER}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DATABASE_NAME=NewsPipe
    depends_on:
      - "postgres"
      - "mongo"
    restart: always
    
  mongo:
    build: mongo-docker/.
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=NewsPipe
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongodata:/data
    command: ["--bind_ip_all"]

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - "mongo"
      - "airflow-newspipe"
    ports:
      - "8081:8081"
    restart: always
